name       : nvidia-304-glx-driver
version    : 304.137
release    : 210
source     :
    - http://us.download.nvidia.com/XFree86/Linux-x86_64/304.137/NVIDIA-Linux-x86_64-304.137.run : eb1f56db3a2bea13e3ccde7b5ae14abe8cd6c6dbe69af4c71c68a623cc96e3e2
extract    : no
homepage   : https://nvidia.com
license    :
    - EULA
summary    :
    - NVIDIA 304xx Binary Driver (LTS Kernel)
    - common : Shared assets for the NVIDIA 304xx GLX Driver
    - current : NVIDIA 304xx Binary Driver (Current Kernel)
    - modaliases : Files to help with DoFlicky driver detection
component  :
    - kernel.drivers
    - common : xorg.driver
    - current : kernel.drivers
    - modaliases : kernel.drivers
    - 32bit : xorg.driver
description: |
    NVIDIA Binary Driver
rundeps    :
    - common :
        - linux-driver-management
        - libva-vdpau-driver
        - libglvnd
    - 32bit :
        - nvidia-304-glx-driver-common
        - libva-vdpau-driver-32bit
        - libglvnd-32bit
    - main : nvidia-304-glx-driver-common
    - current : nvidia-304-glx-driver-common
conflicts  :
    - common :
        - nvidia-340-glx-driver-common
        - nvidia-glx-driver-common
patterns   :
    - common : /*
    - modaliases :
        - /usr/share/doflicky/modaliases
        - /usr/share/linux-driver-management/modaliases
    - 32bit : /usr/lib32
    - main : /lib/modules/*.lts
    - current : /lib/modules/*.current
strip      : no
debug      : no
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libelf)
    - pkgconfig(xorg-server)
    - pkgconfig(xv)
    - pkgconfig(xvmc)
    - linux-lts
    - linux-lts-headers
    - linux-current
    - linux-current-headers
permanent  :
    - /lib/modules
setup      : |
    sh $sources/NVIDIA-Linux-x86_64-$version.run --extract-only
    pushd NVIDIA*

    # Prepare kernel trees
    cp -a kernel lts_kernel
    cp -a kernel current_kernel

    # Patch kernels
    pushd lts_kernel
    %patch -p1 < $pkgfiles/nv-drm.patch
    popd

    pushd current_kernel
    %patch -p2 < $pkgfiles/0001-kernel-Port-nv-drm-to-4.14-legacy-DRM-API.patch
    %patch -p1 < $pkgfiles/buildfix_kernel_4.15.patch
build      : |
    # The older NVIDIA drivers don't like -C so we pushd.

    # Build LTS kernel modules
    pushd lts_kernel
    %make SYSSRC="/lib/modules/%kernel_version_lts%/build" module
    popd

    # Build current kernel modules
    pushd current_kernel
    %make SYSSRC="/lib/modules/%kernel_version_current%/build" module
install    : |
    # Install LTS kernel drivers
    install -D -d -m 00755 $installdir/lib/modules/%kernel_version_lts%/kernel/drivers/video
    install -m 00644 lts_kernel/*.ko $installdir/lib/modules/%kernel_version_lts%/kernel/drivers/video/.

    # Install current kernel drivers
    install -D -d -m 00755 $installdir/lib/modules/%kernel_version_current%/kernel/drivers/video
    install -m 00644 current_kernel/*.ko $installdir/lib/modules/%kernel_version_current%/kernel/drivers/video/.

    # Prepare modaliases from the LTS kernel
    sh -e $pkgfiles/nvidia_supported nvidia ${package} README.txt lts_kernel/nvidia.ko > modalias
    install -D -m 00644 modalias $installdir/usr/share/doflicky/modaliases/${package}.modaliases

    # New location, keep the old one around for a short while
    install -D -m 00644 modalias $installdir/usr/share/linux-driver-management/modaliases/${package}.modaliases

    # Install nvidia driver for xorg
    install -D -m 00755 nvidia_drv.so $installdir/%libdir%/xorg/modules/drivers/nvidia_drv.so

    # Install all binaries
    install -D -d -m 00755 $installdir/usr/bin
    install -m 00755 `find . -maxdepth 1 -type f -name "nvidia-*" -executable` $installdir/usr/bin/.
    rm -v $installdir/usr/bin/nvidia-installer

    # Install all libraries
    install -D -d -m 00755 $installdir/usr/lib{32,64}
    install -m 00755 lib*.so* $installdir/%libdir%/.
    install -m 00755 tls/lib*.so* $installdir/%libdir%/.
    install -m 00755 32/lib*.so* $installdir/usr/lib32/.
    install -m 00755 32/tls/lib*.so* $installdir/usr/lib32/.

    # Strip OpenCL
    rm -v $installdir/usr/lib{32,64}/libOpenCL.so.1.0.0

    function redo_libs() {
        for gl in $* ; do
            i=`dirname ${gl}`
            clean=`echo $(basename ${gl})|sed -e 's@\.so\.%version%@@g'`
            if [[ ! -e $i/${clean}.so.2 ]] ; then
                if [[ ! -e $i/${clean}.so.1 ]] && [[ ! -e $i/${clean}.so.0 ]] ; then
                    ln -sv `basename ${gl}` $i/${clean}.so.1
                fi
            fi
            if [[ ! -e $i/{clean}.so ]]; then
                ln -sv `basename ${gl}` $i/${clean}.so
            fi
        done
    }

    redo_libs $installdir/usr/lib64/lib*.so.%version%
    redo_libs $installdir/usr/lib32/lib*.so.%version%

    # Nuke stuff that isnt allowed to persist.
    rm -v $installdir/%libdir%/libglx.so*

    # Now move the GL providers out into glx-provider tree
    install -d -D -m 00755 $installdir/usr/lib{32,64}/nvidia
    mv -v $installdir/%libdir%/libGL.so* $installdir/%libdir%/nvidia/.
    mv -v $installdir/usr/lib32/libGL.so* $installdir/usr/lib32/nvidia/.

    # Move vdpau into the final position
    install -D -d -m 00755 $installdir/usr/lib{32,64}/vdpau
    mv -v $installdir/%libdir%/libvdpau* $installdir/%libdir%/vdpau/.
    mv -v $installdir/usr/lib32/libvdpau* $installdir/usr/lib32/vdpau/.

    # Remove vendored libvdpau nonsense
    rm -fv $installdir/usr/lib{32,64}/vdpau/libvdpau{,_trace}.so*

    # Data files
    install -D -m 00644 nvidia-settings.desktop $installdir/usr/share/applications/nvidia-settings.desktop
    sed -e 's@__UTILS_PATH__@/usr/bin@' -e 's@__PIXMAP_PATH__@/usr/share/pixmaps@' -i $installdir/usr/share/applications/nvidia-settings.desktop
    install -D -m 00644 nvidia-settings.png $installdir/usr/share/pixmaps/nvidia-settings.png
    install -D -m 00644 nvidia.icd $installdir/usr/share/OpenCL/vendors/nvidia.icd

    # Blacklist nouveau
    install -D -m 00644 $pkgfiles/nvidia.conf $installdir/usr/lib/modprobe.d/nvidia.conf

    # Additional files
    install -D -m 00644 $pkgfiles/71-nvidia.rules $installdir/%libdir%/udev/rules.d/71-nvidia.rules

    # Make sure our glx is found, LDM will handle the main config file
    install -D -m 00644 $pkgfiles/xorg.conf $installdir/usr/share/X11/xorg.conf.d/10-nvidia.conf
    install -D -m 00644 libglx.so.${version} $installdir/%libdir%/nvidia/modules/libglx.so
    ln -sv libglx.so $installdir/%libdir%/nvidia/modules/libglx.so.1

    # Make our non glvnd libraries usable by masking glvnd libGL
    install -D -m 00644 $pkgfiles/ld.so.conf $installdir/usr/share/ld.so.conf.d/00-nvidia.conf
